/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Farm {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'location' : string,
}
export interface Product {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'unit' : string,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : number,
  'farmId' : bigint,
}
export interface _SERVICE {
  'getAllFarms' : ActorMethod<[], Array<Farm>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getFarmById' : ActorMethod<[bigint], Farm>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getProductsByFarmId' : ActorMethod<[bigint], Array<Product>>,
  'searchProductsByName' : ActorMethod<[string], Array<Product>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];